name: "cache"
on:
  push:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: nixos-20.09 (Linux)
          channel: nixos-20.09
          os: ubuntu-latest
        - name: nixpkgs-unstable (Linux)
          channel: nixpkgs-unstable
          os: ubuntu-latest
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: "Setup SSH key"
      run: |
        mkdir -p -m 0700 ~/.ssh
        echo "StrictHostKeyChecking no" >> ~/.ssh/config
        echo "IdentityFile ~/.ssh/id_ed25519" >> ~/.ssh/config
        echo "UserKnownHostsFile /dev/null" >> ~/.ssh/config
        printenv SSH_KEY >> ~/.ssh/id_ed25519
        chmod 0600 ~/.ssh/id_ed25519
      env:
        SSH_KEY: '${{ secrets.SSH_KEY }}'
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:${{ matrix.channel }}
    - uses: cachix/cachix-action@v7
      with:
        name: hmenke
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build
